#! /usr/bin/env python
# encoding: utf-8
# Thomas Nagy, 2006-2010 (ita)

# the following two variables are used by the target "waf dist"
VERSION='0.0.1'
APPNAME='acromag'

# these variables are mandatory ('/' are converted automatically)
top = '.'
out = 'build'

def set_options(opt):
	opt.tool_options('compiler_cc')

def configure(conf):
	conf.check_tool('compiler_cc')

def build(bld):
	bld(
		features = 'cc',
		source = bld.path.ant_glob('**/*.c', excl = 'drvr230.c'),
		ccflags  = ['-Wall', '-ggdb'],
		target = 'ip230',
		includes = '. ../carrier /usr/include'
		)
	bld(
		features = 'cc cprogram',
		source = 'drvr230.c',
		ccflags  = ['-Wall', '-ggdb'],
		target = 'a.out',
		libs   = 'm',
		includes = '. ../carrier /usr/include',
		add_objects = ['carrier', 'ip230'])

	bld.add_subdirs('../carrier')

