#! /usr/bin/env python
# encoding: utf-8
# Thomas Nagy, 2006-2010 (ita)

# the following two variables are used by the target "waf dist"
VERSION='0.0.1'
APPNAME='acromag'

# these variables are mandatory ('/' are converted automatically)
top = '.'
out = 'build'

def set_options(opt):
	opt.tool_options('compiler_cc')

def configure(conf):
	conf.check_tool('compiler_cc')

def build(bld):

	bld(
		features = 'cc',
		source = bld.path.ant_glob('**/*.c', excl = 'drvr330.c'),
		target = 'ip330',
		ccflags  = ['-Wall', '-ggdb', '-fPIC'],
		includes = '. ../carrier /usr/include'
		)
	bld(
		features = 'cc cprogram',
		source = 'drvr330.c',
		target = 'a.out',
		ccflags  = ['-Wall', '-ggdb', '-std=c99'],
		includes = '. ../carrier /usr/include',
		add_objects = ['carrier', 'ip330'])

	bld.add_subdirs('../carrier')

